// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTodoApp.API.DbContext;

#nullable disable

namespace MyTodoApp.API.Migrations
{
    [DbContext(typeof(TodoDataContext))]
    [Migration("20260216135100_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("MyTodoApp.API.Entities.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDone = false,
                            Priority = 0,
                            Title = "Rydde garasjen"
                        },
                        new
                        {
                            Id = 2,
                            DueDate = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = false,
                            Priority = 2,
                            Title = "Ta oppvasken"
                        },
                        new
                        {
                            Id = 3,
                            IsDone = false,
                            Priority = 1,
                            Title = "Handle matvarer"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Luftfukter",
                            IsDone = true,
                            Priority = 1,
                            Title = "Hente pakke"
                        });
                });

            modelBuilder.Entity("MyTodoApp.API.Entities.TodoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TodoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TodoId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gulost",
                            IsDone = false,
                            TodoId = 3
                        },
                        new
                        {
                            Id = 2,
                            Description = "Skinke",
                            IsDone = false,
                            TodoId = 3
                        });
                });

            modelBuilder.Entity("MyTodoApp.API.Entities.TodoTask", b =>
                {
                    b.HasOne("MyTodoApp.API.Entities.Todo", "TodoItem")
                        .WithMany("Tasks")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoItem");
                });

            modelBuilder.Entity("MyTodoApp.API.Entities.Todo", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
